# Generated by Django 5.0.6 on 2024-06-15 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_audio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='audio',
            unique_together={('user', 'name')},
        ),
    ]
