# Generated by Django 5.0.6 on 2024-06-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_audio_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='audio/preview_image/'),
        ),
    ]
